### ISSUE TITLE
Required permissions

### ISSUE THREAD

**Issue by norpol** [dessant/youtube-video-quality#1]
Hi! I'd love to give this extension a try, but I'm worried because the extension needs to access all data on all websites - this might even cause trouble without you as a bad actor due to possible vulnerabilities. Could we maybe update the documentation or change the required permissions?

**Comment by dessant** [comment]
It's not expected that the required hosts will change much, so it's fine to restrict host permissions at this point.

**Comment by norpol** [comment]
Do you know where this is configured?
Also tried to figure out which domains are affected. I guess mostly `*.youtube.com`?

**Comment by Julianoe** [comment]
I came here to say this. I want to use this extension but the required permissions seem unnecessarily large

**Comment by terr72** [comment]
Any update on this issue?
This is something that concerns me as well and actually prevents me from installing the extension.
It would also be a good idea to get rid of the message "This extension isn’t monitored by Mozilla. Make sure you trust the extension before you install it." on the Firefox Addons site.

**Comment by dessant** [comment]
The extension needs to be updated because it currently does not work as expected, the video stream does not always switch to HD, despite HD quality being selected automatically in player settings. I cannot anticipate if any host permissions will be required for the fix, and I do not have time to look into this issue for the forseeable future.

Those concerned are advised to either look for a different extension, or fork this one and republish it with the desired changes.

Also worth noting that even when the host will be restricted to YouTube domains, that still gives the extension access to your Google account, and through Gmail it could possibly gain access to all your other accounts where passwords are resettable.

I intend to restrict host permissions, though in this case restricted hosts wouldn't be too helpful in reducing your exposure if the extension becomes malicious.

So ultimately it comes down to either trusting the author when installing an extension, or auditing every version yourself.

**Comment by dessant** [comment]
Unnecessary permissions have been removed in https://github.com/dessant/youtube-video-quality/commit/66508b901bf26e3b787f8cd5d038f21dea934a5e.

**Comment by terr72** [comment]
Thank you very much for limiting the rights. Can't wait to see an updated version on AMO.

**Comment by dessant** [comment]
I've just published the latest version on AMO. If you're concerned about the message about the extension not being monitored by Mozilla, you can nominate the extension for the Recommended Extensions program, the updates of those extensions are reviewed by Mozilla employees before they are published.

https://support.mozilla.org/en-US/kb/recommended-extensions-program#w_may-i-suggest-extensions-to-become-recommended

**Comment by terr72** [comment]
Thanksfor the hint, I just submitted a nomination for the addon.
