### ISSUE TITLE
Video quality settings selection not sticking

### ISSUE THREAD

**Issue by Vafarien** [dessant/youtube-video-quality#22]
**System**

* OS name: [ Windows ]
* OS version: [ Version 10.0.19045 , Build 19045 ]
* Browser name: [ Chrome ]
* Browser version: [ Version 112.0.5615.138 (Official Build) (64-bit) ]
* Extension version: [ Version 2.0.0 ]

**Bug description**

Video quality settings for youtube Extension isn't working properly anymore, because when i select 1440p for default, the extension does not retain the setting, upon refreshing the options page it's always reverting to 480p, the dark mode setting retains memory, but not the quality option, this issue only seemed to start after the yearly avocado pop-up.
i right click it and select options,
i see 480p, and the dropdown of all other qualitys,
i select 1440p
i go back to youtube video
it's still forcing 480p even though higher resolutions are available
i go back to options for the extension, it hasn't remembered my setting, and keeps going back to 480p even upon refresh.

i would like to continue using the extension, but for now i have disabled it in my browser extensions, because it's no longer serving its function.

**Comment by Vafarien** [comment]
Tested on a "Free with Ads" Youtube movie: [https://www.youtube.com/watch?v=NrPjgEQPips](Link)
Max video Quality 1080p
Issue may be in relation to Youtube using Chrome's widevine DRM system, because upon attempting to take a screenshot whole video goes black, but can be watched normally when not taking screenshots with Windows Snipping tool:
![image](https://user-images.githubusercontent.com/2349950/233558298-266884d7-1d9b-4030-a22e-1307febc7621.png)

**Comment by dessant** [comment]
I can't yet reproduce the issue with other videos, and the video you shared is saying "The uploader has not made this video available in your country".

I think the quality setting itself is saved, you could check this by selecting a new video quality and immediately refreshing the options page, without visiting a video.

It's possible that these types of restricted videos store the video quality options differently, and that in turn triggers the extension to store the 480p value, because it thinks that you have selected a new quality through the YouTube player settings.

Has the new tab with the contribution page appeared right when you visited a youtube page, or did you change the video quality through the player or the extension options and that's when the new tab was opened?

**Comment by Vafarien** [comment]
Tested on a normal non-movie youtube video [https://www.youtube.com/watch?v=kyuAJgMsRsM](YoutubeLink)
1440p Settings in extension retain memory of setting and stay 1440p after refresh.
it seems only when watching specialized youtube content the extension defaults all other youtube tabs and content to 480p.
seemingly not retaining a tab per tab basis sandbox of quality settings.
i don't know if there's anything you can do about it.
i guess the extension inherits the most active tabs youtube session and defaults to 480p which i can't override unless disabled. when only watching unique youtube videos such as movie links.
my assessment is that the extension is functioning as good as it can, but anything outside normal youtube content makes the extension revert to default settings, until re enabled on a normal youtube video.
