### ISSUE TITLE
Toolbar icon.

### ISSUE THREAD

**Issue by SunRaysFalls** [dessant/youtube-video-quality#7]
Please add an icon for the addon in the adress bar, where all the other addons are, or add an icon on youtube directly that will lead to settings page for the addon. Going in addons page is counterintuitive,

**Comment by dessant** [comment]
I don't yet see a reason to add a toolbar icon and popup, because the video quality setting can be directly controlled from YouTube's player settings. If you change the video quality there, the extension will remember it.

If there will be other options for the extension that need frequent changing in the future, I'll reconsider adding a toolbar button.
